FPS = 60

COLORS_PLAYER_1 = (255,60,60)
COLORS_PLAYER_2 = (60,60,255)
COLORS_TILE_BACKGROUND = 'gray'
COLORS_TILE_TEXT = 'black'
COLORS_WINDOW_BACKGROUND = 'black'
COLORS_WINDOW_TEXT = 'white'
COLORS_CURSOR = 'orange'
COLORS_TILE_HIGHLIGHT = 'green'

GAME_TITLE = "pThinkAhead v.01"
GAME_MINIMUM_TILE_VALUE = -20
GAME_MAXIMUM_TILE_VALUE = 20

FONT_SIZE = 18
SCREEN_HEIGHT = 600
SCREEN_WIDTH = 800
TILE_SIZE = 60
GAME_ROWS = 10
GAME_COLS = 10

MYSTERY_BOX_CHARACTER = '?'
CURSOR_CHARACTER = '@'